# This is a basic workflow to help you get started with Actions

name: ryousyoku

# Controls when the workflow will run
on:
  schedule:
   - cron: '30 6 * * *'
  # Triggers the workflow on push or pull request events but only for the main branch
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sent:
    # The type of runner that the job will run on
    name: sent ryousyoku
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install numpy
          pip install pandas
          pip install load_workbook
          pip install pytz
          pip install tweepy
      - name: Run script
        run:
          python ryousyoku-bot.jpynb
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
